### ISSUE TITLE
Problem with BIOS 

### ISSUE THREAD

**Issue by hmthang96** [akarsh1995/ASUS-TUF-Gaming-B460-Plus-i5-10400-Opencore-Hackintosh-Build#1]
Everything seem be ok, i installed the MacOS to my PC and it worked perfectly.
But I got a problem with BIOS. When every i reboot or start the PC, it go to the Safe mode.
The system has POSTed in safe mode.
It may be due to the previous POST attemp failing because of system instability.

Do you get the same problem ?

**Comment by akarsh1995** [comment]
Did you mean this screen ??
 ![bios-error-screen.jpg](https://user-images.githubusercontent.com/25827628/99003664-71bb7500-2564-11eb-93bf-e3493717a57a.jpg)

**Comment by hmthang96** [comment]
> Did you mean this screen ??
> ![bios-error-screen.jpg](https://user-images.githubusercontent.com/25827628/99003664-71bb7500-2564-11eb-93bf-e3493717a57a.jpg)

Yes !!!

**Comment by akarsh1995** [comment]
> Everything seem be ok, i installed the MacOS to my PC and it worked perfectly.
> But I got a problem with BIOS. When every i reboot or start the PC, it go to the Safe mode.
> The system has POSTed in safe mode.
> It may be due to the previous POST attemp failing because of system instability.
> 
> Do you get the same problem ?

I had this problem but the problem did go away after resolving RTC issues. Most motherboards get fixed by setting `Kernel -> Quirks -> DisableRtcChecksum -> True` in the config plist. It is already set in the [sample_config.plist](https://github.com/akarsh1995/ASUS-TUF-Gaming-B460-Plus-i5-10400-Opencore-Hackintosh-Build/blob/542b2674a584b20e2a0b1eabf03ed202747966d0/OC/sample_config.plist#L667) provided. Kindly check in yours. But sometimes it should be manually fixed. 

First you can actually check if RTC writing to bad region is causing this issue in the first place. 

Download [RTC memory fixup](https://github.com/acidanthera/RTCMemoryFixup/releases/tag/1.0.6), add to kexts and add a boot arg `rtcfx_exclude=00-FF` located `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args`, of course, first include the RTCMemoryFixup.kext kext in `Kernel -> Add` 

This is suffice to check if RTC writing to a bad region is causing this. If it's fixed then you have to drill down further finding the bad region. Follow this guide [Finding out bad RTC region](https://dortania.github.io/OpenCore-Post-Install/misc/rtc.html#finding-our-bad-rtc-region)

**Comment by hmthang96** [comment]
> > Everything seem be ok, i installed the MacOS to my PC and it worked perfectly.
> > But I got a problem with BIOS. When every i reboot or start the PC, it go to the Safe mode.
> > The system has POSTed in safe mode.
> > It may be due to the previous POST attemp failing because of system instability.
> > Do you get the same problem ?
> 
> I had this problem but the problem did go away after resolving RTC issues. Most motherboards get fixed by setting `Kernel -> Quirks -> DisableRtcChecksum -> True` in the config plist. It is already set in the [sample_config.plist](https://github.com/akarsh1995/ASUS-TUF-Gaming-B460-Plus-i5-10400-Opencore-Hackintosh-Build/blob/542b2674a584b20e2a0b1eabf03ed202747966d0/OC/sample_config.plist#L667) provided. Kindly check in yours. But sometimes it should be manually fixed.
> 
> First you can actually check if RTC writing to bad region is causing this issue in the first place.
> 
> Download [RTC memory fixup](https://github.com/acidanthera/RTCMemoryFixup/releases/tag/1.0.6), add to kexts and add a boot arg `rtcfx_exclude=00-FF` located `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args`, of course, first include the RTCMemoryFixup.kext kext in `Kernel -> Add`
> 
> This is suffice to check if RTC writing to a bad region is causing this. If it's fixed then you have to drill down further finding the bad region. Follow this guide [Finding out bad RTC region](https://dortania.github.io/OpenCore-Post-Install/misc/rtc.html#finding-our-bad-rtc-region)

Hmmm, when i tried this method and i saw that my Hackintosh always set to 7:00am 31.12.1999 when i restart.

I think I will find another way to fix this. ^_^

**Comment by akarsh1995** [comment]
@hmthang96 Pull the latest changes it might fix RTC issue. I have updated acpi today with newly built ssdt-awac.aml using ssdt time instead of pulling a prebuilt one.


Also, if you have windows installed, boot it via opencore bootloader only. If you boot via efi # bootloader (pressing F8) it might break the bios. It might not mess with the clock.

Let me know once you get it fixed.

**Comment by hmthang96** [comment]
> @hmthang96 Pull the latest changes it might fix RTC issue. I have updated acpi today with newly built ssdt-awac.aml using ssdt time instead of pulling a prebuilt one.
> 
> Also, if you have windows installed, boot it via opencore bootloader only. If you boot via efi # bootloader (pressing F8) it might break the bios. It might not mess with the clock.
> 
> Let me know once you get it fixed.

I turned off DisableRTCChemksum and turned it on again, and it worked perfect ^_^

You can try this methods that I found on here to fix the clock of Windows and Hackintosh problem.
https://github.com/xiaoMGitHub/LEGION_Y7000Series_Hackintosh
He makes the Hackintosh to use Local time instead of RTC
