### ISSUE TITLE
Disable dGpu

### ISSUE THREAD

**Issue by antoniopanariello2000** [akarsh1995/ASUS-TUF-Gaming-B460-Plus-i5-10400-Opencore-Hackintosh-Build#2]
So, I install successfully Macos, but it reads Intel graphic card with only 7 mb of memory. If I try to use your file to disable gpu, Macos not load. I also try to use the opencore boot option "-wegnoegpu", but MacOs don't load. If I unplug the graphic card from the motherboard it work, exceptional that I have a pink screen. So, how I can disable the dGpu and use the Intel grapich Card with abouyt 1000 Mb of memory?

**Comment by akarsh1995** [comment]
@antoniopanariello2000 

First and foremost update the BIOS version, if not updated, to the mentioned version i.e. 1401.

Most likely this issue is caused by: BIOS configuration DMVT allocation.
If you used the the bios profile from the repo this should not be the case. Still double check whether your configuration tally with the image below.

![IMG_20201126_222043](https://user-images.githubusercontent.com/25827628/100377197-cd8eff00-3036-11eb-9154-6649c6f2cb58.jpg)

Since you already tried `-wegnoegpu` I also wanted you to make sure you also turn [true -> false](https://github.com/akarsh1995/ASUS-TUF-Gaming-B460-Plus-i5-10400-Opencore-Hackintosh-Build/blob/ca62e966a8c6636bd767723730396f491abaf15f/OC/sample_config.plist#L31) in config.plist file

After all these mentioned checks applied let me know the status. If resolved we can move ahead to permanently disable dGPU.

**Comment by akarsh1995** [comment]
@antoniopanariello2000 
I also had magenta monitor screen issue resolved it watching this [Hackintosh Magenta Screen Resolved](https://www.youtube.com/watch?v=JlcqAwoNz-Y) 

You'll encounter copy permission issues. So you have to disable system integrity protection and then copy the generated directory to the destination.

**Comment by antoniopanariello2000** [comment]
@akarsh1995 
In my BIOS the graphics settings don't come out. Here is the problem !!

![20201126_185252](https://user-images.githubusercontent.com/37624012/100381298-fdc7a500-3018-11eb-9258-9167e63336e0.jpg)

**Comment by akarsh1995** [comment]
> @akarsh1995
> In my BIOS the graphics settings don't come out. Here is the problem !!
> 
> ![20201126_185252](https://user-images.githubusercontent.com/37624012/100381298-fdc7a500-3018-11eb-9258-9167e63336e0.jpg)

BIOS Version ??

**Comment by antoniopanariello2000** [comment]
![Bios](https://user-images.githubusercontent.com/37624012/100436651-eda6d880-309f-11eb-8ce0-26f61ea82f9c.png)

**Comment by akarsh1995** [comment]
@antoniopanariello2000 

ASUS BIOS version ??

I've updated readme. Look for installation notes.
